name: reservation
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-271.7.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  logger: ^1.1.0
  hooks_riverpod: ^2.0.2
  syncfusion_flutter_calendar: ^20.3.50
  syncfusion_localizations: ^20.3.50

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.1.1
  build_runner: ^2.2.1
  json_serializable: ^6.5.0

flutter:
  uses-material-design: true
  generate: true
